### PR TITLE
Updated SS4 screenshot

### PR DESCRIPTION
**Pull request by nicolewilliams16**

### CODE REVIEW

**Comment by robbieaverill** [comment]
`docs/en/_images/preview-options.png` - the original screenshot is from the draft/published preview state in the lower RHS - the new screenshot is the draft/publish action buttons in the LHS

**Comment by robbieaverill** [comment]
I'm gonna mute this PR until it's ready - can you tag me in a comment when you're finished @nicolewilliams16 ?

**Comment by nicolewilliams16** [comment]
@robbieaverill the original screenshot is incorrect, it's talking about the publishing bar on the LHS but as you've pointed out it's a picture of the mode viewer on the RHS, I've updated the correct image and split out "mode viewer" as new section with it's own screenshot.

**Comment by nicolewilliams16** [comment]
@robbieaverill hold off merging, I'll update the file names so it's clearer at the image level too

**Comment by robbieaverill** [comment]
Ok, great!

**Comment by nicolewilliams16** [comment]
@robbieaverill ok go ahead and merge away please :)

**Pull request merged**
